name: Terraform OCI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure OCI
        env:
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.oci

          printf '%s\n' "$OCI_CONFIG" > ~/.oci/config
          printf '%s\n' "$OCI_PRIVATE_KEY" > ~/.oci/oci_api_key.pem

          chmod 600 ~/.oci/config
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out="tfplan"

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan


  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure OCI
        env:
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.oci

          printf '%s\n' "$OCI_CONFIG" > ~/.oci/config
          printf '%s\n' "$OCI_PRIVATE_KEY" > ~/.oci/oci_api_key.pem

          chmod 600 ~/.oci/config
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan